.PHONY: atcoder
atcoder:
	cp ../template/atcoder.rs ./main.rs
	cat ../template/template.rs >> ./main.rs

.PHONY: aoj
aoj:
	cp ../template/aoj.rs ./main.rs
	cat ../template/template.rs >> ./main.rs

.PHONY: codeforces
codeforces:
	cp ../template/codeforces.rs ./main.rs
	cat ../template/template.rs >> ./main.rs
